// <auto-generated />
using CodeFirst.Infrastructure.Settings;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirst.Infrastructure.Migrations
{
    [DbContext(typeof(CodeFirstContext))]
    [Migration("20210508224836_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodeFirst.Domain.Entities.Persona", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PersonaId")
                        .HasComment("Identificador de la persona")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Apellido")
                        .HasComment("Apellido de la persona");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int")
                        .HasColumnName("DepartamentoId")
                        .HasComment("Identificador del departamento");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Nombre")
                        .HasComment("Nombre de la persona");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NumeroDocumento")
                        .HasComment("Nombre de la persona");

                    b.Property<string>("TipoDocumentoId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("TipoDocumento")
                        .HasComment("Tipo de documento");

                    b.HasKey("PersonaId");

                    b.ToTable("Personas");

                    b.HasData(
                        new
                        {
                            PersonaId = 1,
                            Apellidos = "Candelario Restrepo",
                            DepartamentoId = 1,
                            Nombres = "Erwing 01",
                            NumeroDocumento = "76018789",
                            TipoDocumentoId = "Cedula"
                        },
                        new
                        {
                            PersonaId = 2,
                            Apellidos = "Candelario Restrepo",
                            DepartamentoId = 2,
                            Nombres = "Erwing 02",
                            NumeroDocumento = "76018789",
                            TipoDocumentoId = "Cedula"
                        },
                        new
                        {
                            PersonaId = 3,
                            Apellidos = "Candelario Restrepo",
                            DepartamentoId = 3,
                            Nombres = "Erwing 03",
                            NumeroDocumento = "76018789",
                            TipoDocumentoId = "Cedula"
                        },
                        new
                        {
                            PersonaId = 4,
                            Apellidos = "Candelario Restrepo",
                            DepartamentoId = 4,
                            Nombres = "Erwing 04",
                            NumeroDocumento = "76018789",
                            TipoDocumentoId = "Cedula"
                        },
                        new
                        {
                            PersonaId = 5,
                            Apellidos = "Candelario Restrepo",
                            DepartamentoId = 5,
                            Nombres = "Erwing 05",
                            NumeroDocumento = "76018789",
                            TipoDocumentoId = "Cedula"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
